version: "3.8"
services:
  db:
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql

  web:
    build: ./docker/nginx/local
    ports:
      - 8000:8000
    volumes :
      - ./src:/workspace
    working_dir:
      /workspace
    depends_on:
      - app

  app:
      build: ./docker/python/local
      command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
      volumes:
        - ./src:/workspace
      expose:
        - "8001"
      depends_on:
        - db

volumes:
  db-store:
